### ISSUE TITLE
Identifer names and docs should be written in English, not French

### ISSUE THREAD

**Issue by KOLANICH** [reseau-constellation/client-python#1]
Because English is the current lingua franca, not French.

**Comment by julienmalard** [comment]
Bonjour Kolanich!
Je te remercie pour ton message et ton intérêt dans Constellation. Au sujet de la langue et de l'inclusion, toutes mes opinions et motivations ont déjà été écrites par Gretchen McCulloch beaucoup mieux que je ne pourrais l'écrire moi-même, donc je vais simplement partager son article : https://www.wired.com/story/coding-is-for-everyoneas-long-as-you-speak-english/
Évidemment, notre motivation est d'être le plus inclusif possible. Si tu veux participer au projet en Russe ou dans une autre langue tu seras certainement le bienvenu. Nous travaillons également à traduire l'interface de Constellation, et éventuellement sa documentation et [même son code](https://லஸ்ஸி.இந்தியா) en d'autres langues, le tout en utilisant Constellation elle-même comme base de données distribuée pour les traductions. Si ça t'intéresse, n'hésite pas à faire signe !
Je vais fermer ce signalement pour l'instant parce qu'il ne s'agit pas d'une erreur dans le code, mais n'hésite pas à continuer la discussion ci-dessous.

Au plaisir,
Julien
